- .circleci/config.yml
Muti-host test takes a lot of time to initialize. (~ 10 min)
I want to reduce the time taken for `docker pull`.
For that, I add the job to prepare qcow disk image for docker pull already `/var/lib/docker`.
> Create var-lib-docker qcow image

- mtest/setup-cke.sh
Sometimes `setup-cke.sh` fails like this: https://circleci.com/gh/cybozu-go/cke/1395
This commit resolves the problem by adding wait for vault launch.
> [mtest] stabilize setup-cke.sh

- kubernetes.go
http://man7.org/linux/man-pages/man5/machine-id.5.html
> The machine ID is a single newline-terminated, hexadecimal, 32-character, lowercase ID.
The host name could be invalid machine id.  Mount host's `/etc/machine-id` to the container.
> Use machine-id to identify nodes

- mtest/run_test.go
The current strategy may skip etcd maintenance operations
when the etcd cluster is not perfectly good.  In such cases,
DecideOps may return nil.
This commit adds a check for such cases.
> [mtest] check etcd cluster is good

- commands.go
- docs/etcd.md
- kubernetes.go
- mtest/operators_test.go
- status.go
- strategy.go
- strategy_test.go
To help applications running on Kubernetes use CKE maintained etcd,
CKE creates and maintains a Kubernetes resource `Endpoints` that lists
etcd endpoints addresses.
> Export etcd endpoints to Kubernetes

- mtest/kubernetes_test.go
- op/kube_etcd_endpoints.go
- op/status.go
Kubernetes does not allow Endpoints exists w/o corresponding Service.
Such Endpoints are removed automagically by the endpoints controller.
https://github.com/kubernetes/kubernetes/blob/b7c2d923ef4e166b9572d3aa09ca72231b59b28b/pkg/controller/endpoint/endpoints_controller.go#L392-L397
This commit creates a headless Service "cke-etcd" in "kube-system"
namespace to protect etcd Endpoints from auto removal.
> Add Service for etcd Endpoints resource.

- cluster.go
- cluster_test.go
- docs/cluster.md
- mtest/operators_test.go
- mtest/setup-cke.sh
- mtest/suite_test.go
- op/kube_node_update.go
- server/node_filter.go
- server/strategy.go
- server/strategy_test.go
- vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
- vendor/modules.txt
This series of commits implement:
* validations for miscellaneous items in cluster.yml
* update Kubernetes `Node` resources to have annotations, labels, and taints specified in cluster.yml
Annotations, labels, and taints of nodes are added or updated but not removed.
This is because other applications may add their own annotations, labels, or taints.
> Update node annotations, labels, and taints

- go.mod
- go.sum
- vendor/k8s.io/client-go/pkg/version/base.go
- vendor/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go
- vendor/k8s.io/client-go/transport/round_trippers.go
- vendor/modules.txt
Go 1.11.2 fixes unstable checksum for k8s.io modules.
Unfortunatelly, to correct wrong checksum in go.sum, the dependencies
need to be re-acquired once.
This commit does following:
1. go get k8s.io/client-go@v8.0.0
2. go get k8s.io/api@release-1.11
3. go get k8s.io/apimachinery@release-1.11
4. go mod tidy
5. go mod vendor
6. git add -f vendor go.mod go.sum
> Update Go modules for Go 1.11.2

- container.go
- docs/logging.md
- mtest/kubernetes_test.go
- op/k8s/apiserver_boot.go
- op/k8s/config.go
- op/k8s/controller_manager_boot.go
- op/k8s/kubelet_boot.go
- op/k8s/proxy_boot.go
- op/k8s/rivers_boot.go
- op/k8s/scheduler_boot.go
For easy log collection and rotation, CKE switches to send
logs from its containers to journald instead of files.
Other minor changes include:
- kubelet's OOM score is adjusted to -1000 to avoid OOM killer.
- /var/lib/dockershim for kubelet becomes a plain host directory.
> Send container logs to journald

- docs/ckecli.md
- mtest/ckecli_test.go
- mtest/kubernetes_test.go
- pkg/ckecli/cmd/scp.go
- pkg/ckecli/cmd/ssh.go
Background:
`ckecli ssh NODE` can use only node who is in the cluster member.
It is useless if user want to login to non-member node.
Expect:
`ckecli ssh` and `ckecli scp` can use all nodes regardless cluster
member.
> [ckecli] ssh/scp command can use all nodes regardless cluster member

- mtest/operators_test.go
- op/k8s/proxy_boot.go
- op/k8s/proxy_restart.go
- server/node_filter.go
- server/strategy_test.go
Without this, `kube-proxy` fails to detect local pods for load balancers with
`externalTrafficPolicy` set to `Local`.
> add `--hostname-override` option to kube-proxy.

- mtest/kubernetes_test.go
- op/common/image_pull.go
Image pull may sometimes fail for miscellaneous reasons.
It is safe to retry pull several times, so do it.
> [op] retry image pull command to be more robust

- op/k8s/apiserver_boot.go
NodeRestriction plugin limit a kubelet to modify its own node or pods bound to itself.
> [op] Add NodeRestriction plugin

- op/k8s/apiserver_boot.go
- op/k8s/kubelet_boot.go
- op/k8s/kubelet_restart.go
- op/k8s/proxy_restart.go
- Add command line option to enable node restriction plugin
- Reissue client certs when kubelet and kube-proxy restarted, because the node name may change
> Enable NodeRestriction Plugin

- README.md
- docs/ckecli.md
- docs/k8s.md
- docs/vault.md
- op/common/mkdirs.go
- op/k8s/apiserver_boot.go
- op/k8s/apiserver_restart.go
- op/k8s/config.go
- op/k8s/encryption.go
- pkg/ckecli/cmd/vault_enckey.go
- pkg/ckecli/cmd/vault_init.go
- server/strategy.go
- vault.go
This PR enhances CKE to encrypt `Secret` resources in Kubernetes at rest.
Upgrading of existing installations require `ckecli vault enckey` invocation.
Ref: https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/
> Data encryption at rest

- docker/Dockerfile
We expect to copy CKE binaries to /usr/local/cke/bin/.
However, `docker build` regards /usr/local/cke/bin as a regular file
by definition.
> fix Dockerfile to copy binaries correctly

- CHANGELOG.md
- README.md
- cluster.go
- docs/cluster.md
- docs/k8s.md
- mtest/operators.go
- op/constants.go
- server/node_filter.go
- server/strategy_test.go
With this PR, CKE adds a label `cke.cybozu.com/master: "true"` to control plane nodes.
A new boolean flag `taint_control_node` is added to `cluster.yml`.
When enabled, control plane nodes are tainted with `cke.cybozu.com/master`
whose effect is `PreferNoSchedule`.
> Add labels and taints to control plane nodes

- docs/ckecli.md
- infrastructure.go
- kubeconfig.go
- pkg/ckecli/cmd/infrastructure.go
- pkg/ckecli/cmd/kubernetes_issue.go
- pki.go
Issuing for non-admin users' certificates by `ckecli kubernetes issue` command is quite useful for debugging purposes.
Thus, this pull request made the following changes. 
- add options `--group` and `--user` to `ckecli kubernetes issue` command in order to create non-admin users' certificates
- reflect the changes to the documents.
> [ckecli] add options to `ckecli kubernetes issue` command

- vault.go
If cke accesses while vault is initializing, then vault returns io.EOF and the secret is nil
> [vault] Check secret before SetToken()

- op/k8s/kubelet_boot.go
- op/k8s/kubelet_restart.go
- op/status.go
In dctest environment, it takes 20 seconds for kubelet to be ready.
CKE recognizes that kubelet is not ready and restart kubelet.
CKE should wait until kubelet is ready on kubelet-boot-op and kubelet-restart-op.
> wait for kubelet ready

- op/etcd/common.go
Follow default `--etcd-compaction-interval` of kube-apiserver
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
> [op] Change --auto-compaction-retention of the etcd flag to 5m

- op/k8s/apiserver_boot.go
`StorageObjectInUseProtection` is an option to protect from deleting pvc/pv which is currently used by pods.
See [this page](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#storageobjectinuseprotection)
As `cke` is explicitly declaring addmissionPlugins which are enabled in default, this pull request add `StorageObjectInUseProtection` plugin.
> Add `StorageObjectInUseProtection` option to apiserver

- .circleci/config.yml
- RELEASE.md
- bin/env-sonobuoy
- bin/run-sonobuoy.sh
- example/README.md
- example/Vagrantfile
- sonobuoy/.gitignore
- sonobuoy/Makefile
- sonobuoy/PRODUCT.yaml
- sonobuoy/README.md
- sonobuoy/Vagrantfile
- sonobuoy/cke-cluster.yml
- sonobuoy/cke.config
- sonobuoy/cke.config.yml
- sonobuoy/docker-compose.yml
- sonobuoy/etcd-entrypoint.sh
- sonobuoy/etcd.conf.yml
- sonobuoy/setup
- sonobuoy/vault-entrypoint.sh
- sonobuoy/vault.hcl
This PR adds [certified Kubernetes](https://github.com/cncf/k8s-conformance) conformance test to CI.
- `sonobuoy/` directory contains files to run the conformance tests by [heptio/sonobuoy](https://github.com/heptio/sonobuoy).
- Pushes to branches triggers a CircleCI workflow `conformance`.
The workflow holds the test until a human approves to run it.
- Pushing a git tag triggers `release-github` workflow that runs the conformance tests.
If the test succeeds, the workflow creates a GitHub release and attaches the test results to it.
> Run Sonobuoy in CI

- op/status.go
- pkg/ckecli/cmd/resource_set.go
- resource.go
- resource_apply.go
- sabakan/generator.go
- sabakan/generator_test.go
- sabakan/integrate.go
- server/strategy_test.go
- static/cluster-dns.yml
- static/resources.go
To ensure redundancy for `cluster-dns` in case of that more than one pod of `cluster-dns` are located in a node and the node is drained, this pull request made the following changes.
- add `PodDisruptionBudget ` resource for `cluster-dns` deployment.
- modify ops to handle `PodDisruptionBudget ` resource
- refactor unit test as it was unstable
> Add PodDisruptionBudget for cluster-dns

- docs/cluster_overview.md
- docs/sabakan-integration.md
- sabakan/generator.go
- sabakan/generator_test.go
As we are would like to remove Node resource only when the Node is not listed from the result of GraphQL. 
This pull request made the following changes.
- treat `unreachable` nodes in the same way as `unhealthy` nodes. 
- update documents
> Remove code to handle unreachable

- mtest/Makefile
- op/etcd/add.go
In this issue, I add flag volume deletion to etcd-add-member operation to handle the following situation:
1. A cp node is removed without EtcdDestroyMemberOp
2. The cp node re-join to cluster without initializing
3. etcd-add-member fails because of something wrong
> Add flag deletion to etcd-add-member

- mtest/before.go
- mtest/run.go
- mtest/upgrade.go
`looseCheck` in the mtest becomes unnecessary, because the completion check of the CKE server's activity is now observable through `ckecli status` without using the version-dependent internal algorithm.
This PR removes it.
> mtest: remove use of loose check.

- container.go
- go.mod
- infrastructure.go
Now that we are using Go 1.13, Wrapf can be replaced
with fmt.Errorf's %w.
> Purge github.com/pkg/errors

- sabakan/generator.go
- sabakan/integrate.go
This PR remove `workersByRole()` and add `workersByRole` field to `Generator` to improve performance.
> sabakan: Remove workersByRole() to improve performance.

- cluster.go
- cluster_test.go
- docs/cluster.md
- docs/sabakan-integration.md
- example/cke-cluster.yml
- mtest/cke-cluster.yml
- mtest/run.go
- op/k8s/kubelet_boot.go
- op/k8s/kubelet_restart.go
- server/strategy.go
- sonobuoy/cke-cluster.yml
- sonobuoy/cke-cluster.yml.template
pod_subnet was meant to specify Node's spec.podCIDR field
allocation.  But it was not used at all!
To set node.spec.podCIDR, users can specify extra_args for
kube-controller-manager in cluster.yml as follows:
```yaml
options:
kube-controller:
extra_args:
- "--allocate-node-cidrs=true"
- "--cluster-cidr=10.20.0.0/16"
```
Moreover, node.spec.podCIDR is considered as "poor-man's IPAM"
according to https://github.com/kubernetes/kubernetes/issues/57130
Taking these into account, pod_subnet is just removed from the spec.
> Remove pod_subnet field from cluster.yml

- cluster.go
- cluster_test.go
- docs/cluster.md
- op/k8s/config.go
- op/k8s/kubelet_boot.go
- op/k8s/kubelet_restart.go
- op/status.go
- server/node_filter.go
- server/strategy_test.go
- sonobuoy/cke-cluster.yml.template
- status.go
kubelet needs to use the same cgroup driver as Docker
if the container runtime is Docker.
New option "cgroup_driver" is added to KubeletParams
in cluster.yml to choose the cgroup driver to be used.
ref: https://github.com/kubernetes/kubelet/blob/v0.17.6/config/v1beta1/types.go#L404-L409
> Add cgroup driver option to KubeletParams

- op/status.go
- server/node_filter.go
- server/strategy_test.go
- status.go
cgroup_driver should not be changed for already running kubelet.
If cgroup_driver option was wrong, kubelet could not be run.
Changing the option for running kubelet does not make sense.
The option should be applied only when kubelet is _not_ running.
> Do not restart kubelet when cgroup_driver is changed

- mtest/operators.go
- op/status.go
- server/get_status.go
A concurrent reference of a map caused the race because
other goroutines are mutating the map at the same time.
https://app.circleci.com/pipelines/github/cybozu-go/cke/1085/workflows/92fc41ee-55b3-4877-8098-c5edf86ddcd4/jobs/11128/steps
In fact, the map does not need to be updated, so fixing it that way.
In addition, remove redundant tests from `mtest/operators.go`.
> Fix race in server.Controller.GetClusterStatus

- mtest/operators.go
Recover conditions that were accidentally removed in 5f517cc73547bd3536a55128f0d9b105cacc7a15
> mtest: check changes to scheduler configs

- cluster.go
- cluster_test.go
- sabakan/generator.go
- sabakan/generator_test.go
Avoid node duplication due to `Generator.Regenere` after `Generator.Update`.
And add validation for node duplication.
> Avoid node duplication due to regeneration after update

- sonobuoy/worker.cfg
because it seems that `google-sudoers` group sometimes does not
exist when `cloud-init` runs.
c.f. https://cloudinit.readthedocs.io/en/latest/topics/examples.html#including-users-and-groups
> sonobuoy: use 'sudo:' stanza in cloud-config

- images.go
This fixes kube-proxy's bug in IPVS mode.
c.f. https://github.com/kubernetes/kubernetes/issues/92019
> Update kubernetes image to 1.17.6.2

- pkg/ckecli/cmd/reboot_queue.go
- pkg/ckecli/cmd/reboot_queue_add.go
- pkg/ckecli/cmd/reboot_queue_cancel.go
- pkg/ckecli/cmd/reboot_queue_list.go
This PR implements ckecli reboot-queue commands:
- `ckecli reboot-queue add`
- `ckecli reboot-queue list`
- `ckecli reboot-queue cancel`
> reboot: implement ckecli reboot-queue commands

- docs/metrics.md
- metrics/collector.go
- metrics/metrics.go
- metrics/updater.go
- metrics/updater_test.go
- op/reboot_dequeue.go
- server/control.go
- storage.go
- storage_test.go
This PR adds `reboot_queue_entries` metrics to monitor the progress of reboot operation.
> reboot: add reboot_queue_entries metrics

- op/k8s/config.go
- op/k8s/config_test.go
- server/strategy_test.go
Currently, `kubelet` is executed with `oom-score-adj=-1000` which means the OOM killer doesn't kill the `kubelet` if it makes a memory leak.
This PR removes the option `oom-score-adj`, which results to use the default value `-999`, then the OOM killer can kill the `kubelet`.
> Remove defaulting for kubelet OOMScoreAdj.

- docs/reboot.md
- mtest/operators_test.go
- op/constants.go
- op/reboot.go
- op/reboot_dequeue.go
- phase.go
- server/node_filter.go
- server/strategy.go
- server/strategy_test.go
This PR makes a separate operation for uncordoning nodes as follows:
1. cordon and reboot nodes,
2. restart services on the nodes,
3. uncordon the nodes.
This change is required to reboot control plane nodes.
Also, a small bug is fixed (`rebootDequeue` -> `reboot-dequeue`).
> reboot: uncordon rebooted nodes

- docs/ckecli.md
- docs/reboot.md
- docs/schema.md
- mtest/operators_test.go
- pkg/ckecli/cmd/reboot_queue_disable.go
- pkg/ckecli/cmd/reboot_queue_enable.go
- server/control.go
- storage.go
- storage_test.go
This PR adds `ckecli rq enable` and `ckecli rq disable` commands.
They allow us to suspend/resume reboot queue processing.
> reboot: enable/disable reboot queue processing

- cluster.go
- cluster_test.go
- docs/cluster.md
- go.mod
- mtest/operators_test.go
- mtest/run_test.go
- op/k8s/config.go
- op/k8s/config_test.go
- op/k8s/scheduler_boot.go
- server/node_filter.go
- server/strategy.go
- server/strategy_test.go
Currently, if both `config` and one of `extenders`/`predicates`/`priorities` are configured in `KubeSchedulerConfiguration` , cke ignores the `extenders`/`predicates`/`priorities` fields.
This is so confusing that this PR validates both the fields are not configured,
Signed-off-by: H.Muraoka <hiroshi-muraoka@cybozu.co.jp>
> Validate KubeSchedulerConfiguration API version

- docs/ckecli.md
- mtest/operators_test.go
- pkg/ckecli/cmd/reboot_queue_add.go
- pkg/ckecli/cmd/reboot_queue_add_test.go
> ckecli: prevent rebooting multiple control plane nodes.

- .circleci/config.yml
- bin/run-sonobuoy.sh
- cluster.go
- cluster_test.go
- docs/cluster.md
- op/k8s/proxy_boot.go
- op/k8s/proxy_restart.go
- server/node_filter.go
- server/strategy_test.go
- sonobuoy/Makefile
- sonobuoy/cke-cluster.yml.template
- testdata/cluster.yaml
CKE has run kube-proxy only in IPVS mode.
It now allows users to run kube-proxy in any supported mode.
This PR also contains a commit for the sonobuoy test to work around https://github.com/kubernetes/kubernetes/pull/94968
> Add "mode" option for kube-proxy

- op/k8s/apiserver_restart.go
- op/k8s/kubelet_boot.go
- tools/CHANGELOG.md
- tools/rivers/health.go
I misedited `health.go` and removed `wg.Done()`.  This adds back it.
Also, deprecated command-line flags are removed from `kue-apiserver`.
`kubelet` specifies `--pod-infra-container-image` only for Docker runtime.
> rivers: fix a bug in health checker

- cluster.go
- docs/cluster.md
- docs/logging.md
- mtest/cke-cluster.yml
- mtest/kubernetes_test.go
- op/k8s/apiserver_restart.go
- server/node_filter.go
- server/strategy_test.go
This PR adds `audit_log_path` to `APIServerParams`.
Audit logs can be sent to either of journal log or file.
- `audit_log_path` is empty -> journal log
- `audit_log_path` is set -> specified file
`--audit-log-maxage`, `--audit-log-maxbackup`, `--audit-log-maxsize` can be set using `extra_args`.
> server: add AuditLogPath

- .github/workflows/main.yaml
- CHANGELOG.md
- README.md
- container.go
- docker/Dockerfile
- docker/install-tools
- docs/cke-localproxy.md
- docs/cke.md
- infrastructure.go
- localproxy/infrastructure.go
- localproxy/op.go
- localproxy/run.go
- localproxy/status.go
- localproxy/strategy.go
- mtest/Makefile
- mtest/host.ign
- mtest/localproxy_test.go
- mtest/run_test.go
- mtest/suite_test.go
- op/common/mkdirs.go
- op/common/mkfiles.go
- op/k8s/config.go
- op/k8s/proxy_boot.go
- op/k8s/proxy_restart.go
- pkg/cke-localproxy/main.go
- pkg/ckecli/cmd/kubernetes_issue.go
- server/strategy.go
`cke-localproxy` is a controller for running kube-proxy and unbound on the same server as CKE.
`cke-localproxy` allows programs and users on that servers to connect Kubernetes Services.
`cke-localproxy` depends on Docker.
The user account that runs `cke-localproxy` therefore needs to be able to use Docker.
> Add cke-localproxy

- .github/workflows/main.yaml
- .github/workflows/release-images.yaml
- Makefile
release-image workflow failed
https://github.com/cybozu-go/cke/runs/2162971053?check_suite_focus=true
This failure was caused by testing without running etcd container.
However, as the test is redundant, this PR deletes the test.
Signed-off-by: binoue <banji-inoue@cybozu.co.jp>
> Fix release-image workflow

- pkg/cke/main.go
- server/control.go
- storage.go
- storage_test.go
see https://github.com/cybozu-go/cke/issues/441
When the etcd process which connected from clients stops, `concurrency.Session` in the clients is closed.
But some clientv3 functions in the clients are not canceled. This behavior cause hangs on the clients. 
So we need to check the closing of `concurrency.Session`. And cancel contexts if the session is closed.
In CKE server, there are 2 probrems.
1. `election.Campaign` in standby CKE servers hang.
2. The leader server cannot detect the loss of his leadership.
This PR will monitor the closing of `concurrency.Session` and terminate the CKE process.
This will solve the above problems.
> Watch session and leader key

- CHANGELOG.md
- version.go
Release date is set to tomorrow because it is a bit late today.
> Bump version to 1.20.3

- op/etcd/common.go
This `--enable-v2` flag can already be removed because it applies to the CKE-managed etcd cluster.
> Remove --enable-v2 flag

- docs/ckecli.md
- mtest/operators_test.go
- pkg/ckecli/cmd/reboot_queue_cancel_all.go
This PR adds `ckecli reboot-queue cancel-all` command.
> Implement ckecli rq cancel-all

- pkg/ckecli/cmd/ssh.go
`ckecli ssh` uses a custom private key in its ssh connection. The key is specified via `-i` option of `ssh`.
The key is transferred to `ssh` via a FIFO file created at `~/.ssh/ckecli-ssh-key-<PID>`.
Since `ssh` reads the key multiple times, we need to write it the same time.
Previously `ssh` read the key twice, but OpenSSH 8.6p1 reads it three times. So this is the fix.
> Write private key three times in SSH

- op/k8s/apiserver_restart.go
This PR removes a redundant list of the admission plugins which are enabled by default.
The list of default plugins is described in the subsection of `--enable-admission-plugins` in the [`kube-apiserver` options section](https://v1-21.docs.kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/#options).
> Remove redundant list of plugins enabled by default

- op/reboot.go
When there is misconfiguration of PodDisruptionBudgets, the Eviction API returns a 500 Internal Server Error response.
Even in this case, delete non-protected pods.
> Delete non-protected pod when Eviction API returns any kind of errors

- server/strategy.go
- server/strategy_test.go
This PR fixes the structure of EndpointSlices managed by CKE.
Bad:
```
endpoints:
- addresses:
- 10.69.0.18
- 10.69.1.132
- 10.69.0.205
conditions:
ready: true
```
Good:
```
endpoints:
- addresses:
- 10.69.0.18
conditions:
ready: true
- addresses:
- 10.69.1.132
conditions:
ready: true
- addresses:
- 10.69.0.205
conditions:
ready: true
```
> Fix EndpointSlice to list endpoints rather than endpoint addresses

- server/strategy.go
- server/strategy_test.go
This PR improves the CKE strategy to update `kubernetes`/`cke-etcd` Endpoints/EndpointSlices before/after rebooting a CP Node.
This PR also adds tests for the reconciliation of EndpointSlices.
> Update Endpoints/EndpointSlices when rebooting CP Node

- Makefile
- cluster.go
Kubernetes 1.21 provides a validation function for annotations
in k8s.io/apimachinery/pkg/api/validation package.
https://pkg.go.dev/k8s.io/apimachinery/pkg/api/validation#ValidateAnnotations
> Use the right method to validate annotations

- sonobuoy/Makefile
`--rerun-failed` flag is addded to `run` subcommand at v0.54.0 and is meant to be a replacement of `e2e` subcommand.
https://github.com/vmware-tanzu/sonobuoy/releases/tag/v0.54.0
> use `sonobuoy run --rerun-failed` instead of obsoleted `sonobuoy e2e`

- .github/workflows/release-images.yaml
- .github/workflows/sonobuoy.yaml
> follow behavior change between `sonobuoy e2e` and `sonobuoy run --rerun-failed`

- op/etcd/common.go
etcd 3.5.[0-2] has data inconsistency issue.
https://groups.google.com/a/kubernetes.io/g/dev/c/B7gJs88XtQc/m/rSgNOzV2BwAJ
Signed-off-by: zoetrope <a.ikezoe@gmail.com>
> Add `--experimental-initial-corrupt-check` flag for etcd

- sonobuoy/worker-ign.yml
The GCE image of flatcar 3227.2.0 (the latest version when this PR is submitted) has different resolv.conf content from older versions.
CKE cannot bootstrap worker nodes because `docker pull` from public repo fails on worker nodes due to the difference.
> sonobuoy test: follow flatcar 3227.2.0

- docs/cluster.md
- op/k8s/config.go
- op/k8s/config_test.go
- op/k8s/kubelet_boot.go
- server/node_filter.go
part of https://github.com/cybozu-go/cke/issues/545
`--register-with-taints` option is deprecated, so use `RegisterWithTaints` of KubeletConfiguration instead.
kubelet uses the `RegisterWithTaints` field only when initializing Node resources.
After registration, this field does not affect Node resources.
So I fixed the kubelet_boot op to render the RegisterWithTaints at all times if `boot_taints` exists.
https://github.com/kubernetes/kubernetes/blob/v1.23.9/pkg/kubelet/kubelet_node_status.go#L311
> Stop using deprecated --register-with-taints option

- CHANGELOG.md
- version.go
sonobuoy test was passed.
https://github.com/cybozu-go/cke/runs/7798268975?check_suite_focus=true
> Bump version to 1.23.0

- agent.go
- infrastructure.go
- localproxy/infrastructure.go
- op/reboot.go
- pkg/ckecli/cmd/infrastructure.go
- release agent connection immediately after the node's state transition to `rebooting`
- apply dial timeout to ssh session creation
- shorten dial timeout
> Improve agent connection handling during rebooting

- mtest/cluster.yml
This PR fixes an issue that pmctl2 doesn't connect each VM properly. Placemat manages VM information with a hash map where the key is serial. But the node resources defined in cluster.yaml for mtest don't contain serials.
https://github.com/cybozu-go/placemat/blob/27b37fc6a1d26ecc9ff3b03ad237701e8417eb64/v2/pkg/placemat/cluster.go#L117
The serials are calculated with sha1sum as placemat-menu does.
https://github.com/cybozu-go/neco/blob/b394a4de83c0af1d3662649ba6bb4df0348c36db/menu/cluster.go#L263
> Add serials for VMs

- example/wait-up.sh
- sonobuoy/Makefile
part of https://github.com/cybozu-go/cke/issues/556, https://github.com/cybozu-go/neco/issues/2114
- Fix docker-compose download URL
- Fix confirmation of container exit status
- before
```
❯ docker-compose ps setup 
Name          Command         State    Ports
--------------------------------------------
setup   /opt/setup/setup.sh   Exit 0
```
- after
```
❯ docker-compose ps setup
NAME                COMMAND                 SERVICE             STATUS              PORTS
setup               "/opt/setup/setup.sh"   setup               exited (0) 
```
- Changed to check container exit code from `docker inspect` instead of the text information in `docker-compose ps`.
Signed-off-by: kouki <kouworld0123@gmail.com>
> Fixed sonobuoy test failing.

- CHANGELOG.md
- op/k8s/kubelet_boot.go
In #584 I removed the mount of directories related to CNI.
However, during validation with neco, I found that it was necessary to mount it on the pod with HostPath, so I'm reverting it back.
- coild: https://github.com/cybozu-go/neco/blob/ece450914fa84e9bb62203ff743815a18044203b/etc/coil.yaml#L8491-L8496
- cilium: https://github.com/cybozu-go/neco/blob/ece450914fa84e9bb62203ff743815a18044203b/etc/cilium.yaml#L1245-L1252
Signed-off-by: kouki <kouworld0123@gmail.com>
> Mount directories related to CNI on kubelet

- CHANGELOG.md
- server/node_filter.go
- server/strategy_test.go
The map `cke.EtcdClusterStatus.InSyncMembers` is filled by `GetEtcdClusterStatus()` in `op/status.go`.
It holds not only in-sync members but also not-in-sync members and its length is always equal to the length of `cke.EtcdClusterStatus.Members`.
This PR fixes a node filter for checking whether all etcd members are in-sync or not.
This PR also fixes the test of the CKE strategy by updating input data closer to the real.
> Fix node filter to check etcd in-sync status properly

- CHANGELOG.md
- op/etcd/mark.go
- op/status.go
- server/get_status.go
- server/node_filter.go
- server/strategy.go
- server/strategy_test.go
- status.go
This PR adds a decision step of the CKE strategy to maintain half-added etcd members.
See the issue #579 for the details of "half-added members."
This PR also changes a node filter to not try to initialize half-added etcd members.
Fixes: #579 
>  Fix added-but-not-marked etcd members

- .github/workflows/main.yaml
- .github/workflows/release-images.yaml
- .github/workflows/release-tools.yaml
- .github/workflows/sonobuoy.yaml
- mtest/Makefile
- tools/CHANGELOG.md
- tools/Makefile
- Update go to 1.19 to fail the CKE test case
- Update CNI plugins to 1.2.0
Signed-off-by: zeroalphat <taichi-takemura@cybozu.co.jp>
> cke-tools: Update CNI plugins to v1.2.0

- .github/workflows/release-images.yaml
When releasing 1.25 of cke, the binary generation failed and the release could not be made.
The reason for the binary generation failure was that the setting to embed vcs status was enabled.
Since there is no need to embed debug information in the binaries, disable vcs status.
https://github.com/cybozu-go/cke/actions/runs/4260149159/jobs/7414496154
zeroalphat <taichi-takemura@cybozu.co.jp>
> Add buildvcs option to fix build error

- CHANGELOG.md
- example/kustomization.yaml
The Calico manifest currently used in CKE testing is from the master branch and contains pre-release changes.
Since CKE does not need to use the pre-relase manifest of Calico, I have changed the file to use the manifest of the latest version of Calico.
> Fix Calico manifest to latest version

- docs/user-resources.md
- mtest/kubernetes_test.go
- op/nop.go
- op/status.go
- pkg/compile_resources/main.go
- resource.go
- server/control.go
- server/strategy.go
- server/strategy_test.go
- static/resources.go
- status.go
- storage.go
- storage_test.go
This PR adds two features described below.
1. We can customize the order of applying resources.
2. When applying Deployment and Daemonset resources, cke waits to complete the creation or update.
We can specify the resource application order using the `cke.cybozu.com/rank` annotation. 
Please see [docs/user-resources.md](https://github.com/cybozu-go/cke/pull/617/files#diff-6bbb0727cc2dd5e0e6ed4fdc2ed3af852e555c27972e71d1f3ae052ccda095ed) for detail.
And When we create or update Deployment or DaemonSet resources, cke checks if the update or creation is completed.
If it is not completed, cke runs the `nopOp` that does nothing to wait.
> Update user-defined resource applying logic

- bin/env
- bin/env-sonobuoy
- docs/cke.md
- docs/cluster_overview.md
- mtest/run_test.go
- pkg/cke/main.go
- server/control.go
- server/node_filter.go
- server/strategy.go
- server/strategy_test.go
- sonobuoy/README.md
Add a new cli option `max-concurrent-updates`.
It can limit the number of components (kubelet, kube-proxy and rivers) that can be updated simultaneously.
This change will solve the following problems:
- Prevent large amounts access to the Internet
- Prevent large amounts access to APIServer
- Prevent all kubelets from going down
Signed-off-by: zoetrope <a.ikezoe@gmail.com>
> Limit the number of components (kubelet, kube-proxy and rivers) that can be updated simultaneously

- .github/workflows/main.yaml
- .github/workflows/release-images.yaml
- .github/workflows/release-tools.yaml
- .github/workflows/sonobuoy.yaml
- CHANGELOG.md
- tools/CHANGELOG.md
- tools/Makefile
This PR:
- updates Go to 1.20
- updates CNI plugin to 1.3.0
> cke-tools: Update CNI plugins to v1.3.0

- go.mod
- go.sum
I copied https://github.com/cybozu-go/cke/pull/643 to run tests with enough privileges.
> Bump google.golang.org/grpc from 1.52.0 to 1.53.0

- .gitignore
- cluster.go
- cluster_test.go
- docs/cluster.md
- mtest/run_test.go
- op/reboot.go
- op/reboot_decide.go
- pkg/cke/main.go
- server/config.go
- server/control.go
- server/strategy.go
- server/strategy_test.go
- testdata/cluster.yaml
Signed-off-by: zoetrope <a.ikezoe@gmail.com>
> Retry eviction of pod

- metrics/collector.go
- metrics/metrics.go
- metrics/updater.go
- metrics/updater_test.go
- mtest/reboot_test.go
- op/reboot.go
- pkg/cke/main.go
- sabakan/generator.go
- server/control.go
- server/strategy.go
- server/strategy_test.go
Currently, there is an issue with `cke_node_reboot_status` metrics not being reflected correctly in the following cases:
- When drain/uncordon is repeated
- When node additions and deletions occur with sabakan integration
This PR calculates the value of metrics each time they are collected.
As a result we will be able to get correct metrics.
> Fix `cke_node_reboot_status` metrics

- docs/sabakan-integration.md
- sabakan/generator.go
- sabakan/generator_test.go
Add registration and retiring months to node labels.
These labels will be helpful in scheduling pods.
> Add `register-month` and `retire-month` labels

- server/strategy.go
- server/strategy_test.go
`kubelet-restart` op takes a long time.
If a problem occurs during `kubelet-restart` op (e.g. controller-manager crashes), the problem will not be repaired.
In this PR, after one of `kubelet-restart` op is finished, next operation is decided again.
This will be able to repair a problem in a short time.
> Fix blocking by kubelet-restart op

- docs/ckecli.md
- mtest/reboot_test.go
- pkg/ckecli/cmd/reboot_queue_reset_backoff.go
This PR is implementation of following issue.
- https://github.com/cybozu-go/cke/issues/657
Signed-off-by: YZ775 <yuzuki-mimura@cybozu.co.jp>
> add reboot queue backoff reset command

- tools/CHANGELOG.md
part of https://github.com/cybozu-go/cke/issues/666
The latest version of CNI Plugins is still v1.3.0.
https://github.com/containernetworking/plugins/releases/tag/v1.3.0
> Bump cke-tools version to 1.27.0

- tools/RELEASE.md
This PR clarifies the release procedure of cke-tools.
> Refine release procedure of cke-tools

- docs/metrics.md
- metrics/collector.go
- metrics/metrics.go
- metrics/updater_test.go
This PR adds `reboot_queue_enabled` and `reboot_queue_running` metrices.
> Implement reboot-queue status metrices

- .github/workflows/release-images.yaml
There are no steps `actions/setup-go`, so it uses default Go(1.18) and it is incompatible with current CKE.
> add setup-go in release-cke-image

- docs/sabakan-integration.md
- sabakan/generator.go
- sabakan/generator_test.go
This PR removes the following taints, which are used by the Sabakan integration.
- `cke.cybozu.com/state: unhealthy` (NoSchedule)
- `cke.cybozu.com/state: unreachable` (NoSchedule)
The taint must not be set if the machine failure is minor enough to allow the process to run.
When a node cannot communicate, the `node.kubernetes.io/unreachable` (NoExecute) taint is added.
So `cke.cybozu.com/state: unreachable` taint does not work well.
> Remove Unhealthy/Unreachable taint

- container.go
- localproxy/infrastructure.go
From Docker 25.0.0 or 24.0.5, the parsing volume option has been strict.
https://github.com/docker/cli/pull/4415
With the current implementation, the following error occurs when `extra_binds` is used.
So, this PR fixes it so that parsing errors do not happen.
```
root@cke--82-174134-0:~/go/src/github.com/cybozu-go/cke/sonobuoy# ./bin/ckecli --config=./cke.config history | head -n 30
{
"id": "54",
"status": "cancelled",
"operation": "kubelet-bootstrap",
"command": {
"name": "run-container",
"target": "kubelet"
},
"targets": [
"10.174.0.111",
"10.174.0.112",
"10.174.0.113"
],
"info": "",
"error": "Process exited with status 125, cmdline: docker run --log-driver=journald -d --name=kubelet --read-only --network=host --uts=host --pid=host --privileged --tmpfs=/tmp …
```
> Add rw option to extra volumes

- op/reboot.go
- op/reboot_decide.go
- server/control.go
- server/strategy.go
- server/strategy_test.go
In the current CKE, the dequeue operation of cancelled reboot queue entry has lower priority than other operations like drain, reboot, ...etc.
This implementation causes the dequeue operation not to work correctly when we cancel an entry whose node is under operation.
This PR solves the problem by following changes.
- separating dequeue operation between cancelled entry and completed entry
- set dequeue operation of cancelled entry higher
> change priorty of reboot queue cancel

- tools/Makefile
part of https://github.com/cybozu-go/cke/issues/706
This PR updates CNI plugins to v1.4.1.
ref: https://github.com/containernetworking/plugins/releases/tag/v1.4.1
> cke-tools: Update CNI plugins to v1.4.1

- .github/workflows/main.yaml
- .github/workflows/release-images.yaml
- .github/workflows/release-tools.yaml
- .github/workflows/sonobuoy.yaml
Other dependencies have been updated in https://github.com/cybozu-go/cke/pull/719.
> Update actions/setup-go to v5

- server/strategy.go
This commit is for the following situation:
* there is a finished entry in the repair queue, especially failed one
* a new entry with the same target address is queued
* the target machine becomes healthy
The results of health check are indexed by the target machine's address,
not by the entry ID.
Though health check is not executed for a finished entry, check for
another entry with the same target address can change the status of
the failed entry into "succeeded."
This commit prevents it.
> Fix not to change status of repair-queue's finished entry

- mtest/suite_test.go
This PR fixes unstable mtest caused by https://github.com/cybozu-go/cke/pull/726 .
> fix mtest for exponential backoff

- op/reboot.go
- op/reboot_decide.go
- server/strategy.go
In the current CKE, even if `max_concurrent_reboots` is larger than 1, draining is conducted by serial and rebooting is conducted after draining of all drainable node is finished.
This behavior cause long down time of first drained node.
This PR changes the CKE to move rebooting immediately after draining of each node is finished.
In addition, this PR fixes behavior of canceled reboot queue entry.
> change CKE to proceed rebooting immediately after draining of node  is completed

- CHANGELOG.md
- constraints.go
- docs/ckecli.md
- docs/constraints.md
- docs/sabakan-triggered-repair.md
- pkg/ckecli/cmd/constraints_set.go
- sabakan/integrate.go
- sabakan/repairer.go
- sabakan/repairer_test.go
- server/strategy.go
> Delay repair of a rebooting unreachable machine

- mtest/assets_test.go
- mtest/reboot-eviction-dry-run.yaml
- mtest/reboot_test.go
- op/reboot.go
- op/reboot_decide.go
- op/repair_drain_start.go
part of https://github.com/cybozu-go/cke/issues/735
- perform eviction dry-run before actual eviction
- add more logs related to eviction
> perform eviction dry-run during node reboot feature

- CHANGELOG.md
- docs/sabakan-triggered-repair.md
- sabakan/integrate.go
- sabakan/repairer.go
- sabakan/repairer_test.go
> Delay repair of an out-of-cluster unreachable machine

- op/reboot.go
- op/reboot_decide.go
- server/strategy.go
- server/strategy_test.go
This PR adds the ability to delete Daemonset pods set to `updateStrategy: OnDelete` before rebooting.
> Delete 'OnDelete' DaemonSet pods

- CHANGELOG.md
According to [DEVELOP.md](https://github.com/cybozu-go/cke/blob/release-1.28/DEVELOP.md#starting-development-for-a-new-kubernetes-minor-release), clear CHANGELOG at this point.
> clear changelog to prepare 1.29

- tools/CHANGELOG.md
> Bump cke-tools version to 1.29.0

- CHANGELOG.md
- version.go
sonobuoy result: https://github.com/cybozu-go/cke/actions/runs/9868354779
> Bump version to 1.29.0-rc.1

- .github/workflows/main.yaml
- RELEASE.md
- example/README.md
- sonobuoy/Makefile
- sonobuoy/README.md
GitHub Actions' ubuntu runner no longer has `docker-compose` command.
Use `docker compose` subcommand.
> use docker compose v2 in appropriate way

- op/k8s/kubelet_boot.go
If `/sys/fs/cgroup` is set to read-only, we cannot restart kubelet.
So change mount of `/sys` to read-write.
> Set /sys mount of  kubelet as read-write

- docs/sabakan-integration.md
- sabakan/generator.go
- sabakan/generator_test.go
This PR adds (revives) the following taint.
- `cke.cybozu.com/state: unreachable` (NoSchedule)
This taint was removed in https://github.com/cybozu-go/cke/pull/710. However, since `node.kubernetes.io/unreachable` taint alone was not sufficient for our operations, so I'll revives the taint.
> Revive unreachable taint

- sabakan/generator.go
Before this PR, if roles that do not exist in sabakan is written in cke-template,`chooseWorkerTmpl()` always return such role bacause count of it is always zero.
In such a situation, increseWorker does not work.
In this PR, I change `chooseWorkerTmpl()` to skip that role if it has no sabakan machines.
> fix sabakan integration to handle role that is not exist in sabakan

- bin/env
- op/clusterdns/clusterdns.go
- op/nodedns/nodedns.go
This PR supress DNS query logs for cluster-dns and node-dns.
cf.
- https://coredns.io/plugins/log/
- https://nlnetlabs.nl/documentation/unbound/unbound.conf/
> Supress dns log

- CHANGELOG.md
- version.go
part of https://github.com/cybozu-go/cke/issues/799
The sonobuoy test was passed.
https://github.com/cybozu-go/cke/actions/runs/15962240397
> Bump version to 1.32.0
