docs/k8s.md
Add design document for Kubernetes bootstrapping
=> Add design for Kubernetes bootstrapping

.circleci/config.yml, cluster.go, cluster_test.go, commands.go, container.go, docs/cluster.md, etcd_strategy_test.go, images.go, kubeconfig.go, kubernetes.go, kubernetes_strategy.go, kubernetes_strategy_test.go, mtest/Makefile, mtest/kubernetes_strategy_test.go, mtest/run_test.go, status.go, strategy.go
Deploy the following components to control plane nodes.
- [rivers](https://github.com/cybozu-go/cke-tools/tree/master/cmd/rivers) (TCP reverse proxy)
- kube-apiserver
- kube-controller-manager
- kube-scheduler
=> Deploy kubernetes control plane

docs/k8s.md, images.go, kubeconfig.go, kubernetes.go, kubernetes_strategy.go, kubernetes_strategy_test.go, mtest/Makefile, mtest/cke-cluster.yml, mtest/env.go, mtest/etcd_strategy_test.go, mtest/kubeconfig.yml, mtest/kubernetes_strategy_test.go, mtest/run_test.go, mtest/suite_test.go, status.go
- Deploy Kubelet on all nodes
- Deploy rivers on all nodes
=> Deploy worker nodes

RELEASE.md, apierror.go, cmd/cke/main.go, cmd/ckecli/main.go, control.go, docs/api.md, docs/cke.md, docs/ckecli.md, mtest/run_test.go, responses.go, server.go, version.go
* Add two APIs to CKE (`/health`, `/version`)
* Add `-version` flag to `ckecli`
=> Version health

container.go, docs/etcd.md, etcd.go, etcd_strategy.go, etcd_strategy_test.go
=> Etcd version management

images.go, kubeconfig.go, kubernetes.go, kubernetes_strategy.go, kubernetes_strategy_test.go, mtest/kubernetes_strategy_test.go, mtest/run_test.go, status.go
kube-proxyを全ノードに対してデプロイする機能を追加しました。
=> Deploy kubeproxy

.circleci/config.yml, cli/ca.go, cli/vault.go, cmd/cke/main.go, cmd/ckecli/main.go, docs/ckecli.md, docs/schema.md, mtest/run_test.go, mtest/user-data.yml, storage.go, vault.go
In addition, the default config path is changed.
=> Store Vault connection parameters in etcd

cli/vault.go, commands.go, control.go, docs/ckecli.md, docs/etcd.md, docs/vault.md, etcd.go, etcd_strategy.go, etcd_strategy_test.go, images.go, infrastructure.go, kubernetes.go, kubernetes_strategy_test.go, main_test.go, mtest/Makefile, mtest/change_leader_test.go, mtest/etcd_strategy_test.go, mtest/kubernetes_strategy_test.go, mtest/run_test.go, mtest/setup-cke.sh, mtest/suite_test.go, mtest/test.sh, pki.go, status.go, vault.go, watch.go
* issue etcd server's certificate on bootstrap-operation and add-etcd-member-operation.
* issue etcd client's certificate for kube-apiserver and CKE
* use https to connect to etcd
merge after https://github.com/cybozu-go/etcdutil/pull/3
=> [pki] issue etcd server's certificates

agent.go, commands.go, container.go, etcd.go, kubernetes.go, kubernetes_strategy_test.go, mtest/run_test.go, mtest/suite_test.go, status.go
- Stop rivers by `docker kill` instead of `docker stop`
- return stdout/stderr on container engine.
- `docker ps` and `docker inspect` get informations for all containers at a time
=> Improve test

etcd.go, etcd_strategy_test.go, pki.go
- Remove issuring certificate for common_name=etcdctl
- Set ttl=1h for common_name=root
- Enable etcd auth after remaining BootStrap has completed.
=> [pki] Enable etcd auth, Change certificate config

etcd.go, etcd_strategy.go, etcd_strategy_test.go, mtest/run_test.go, status.go
* add `ClusterHealth` field that indicates whether the etcd cluster is healthy
* change `MemberHealth` to `InSyncMembers` that indicates whether the member is synchronized
=> [etcd] fix EtcdClusterStatus

container.go
Prev Inspect function had a TOCTTOU problem.
Retry Inspect from the beginning.
=> [docker] stabilize container inspect

control.go, docs/vault.md, kubernetes.go, kubernetes_strategy.go, kubernetes_strategy_test.go, mtest/cke-cluster.yml, mtest/setup-cke.sh, pki.go, storage.go
This PR enables k8s service accounts.
=> Service Accounts

cluster.go, cluster_test.go, commands.go, docs/cluster.md, docs/k8s.md, go.sum, kubeconfig.go, kubernetes.go, kubernetes_strategy.go, kubernetes_strategy_test.go, mtest/create-rbac/main.go, pki.go, status.go, vendor/modules.txt
https://kubernetes.io/docs/reference/access-authn-authz/rbac/
=> Enable RBAC authorization

cluster.go, cluster_test.go, collections_test.go, commands.go, container.go, docs/cluster.md, etcd.go, kubernetes.go, mtest/cke-cluster.yml
* add `selinux` field to cluster configuration to each node and cluster.
* add `propagation` and `mode` field to `Mount`. it apply to docker volume option.
* set `shared` and `z` option to the shared directory among multiple containers
=> SELinux support

cluster.go, cluster_test.go, collections_test.go, commands.go, container.go, docs/cluster.md, etcd.go, kubernetes.go, kubernetes_strategy_test.go, mtest/cke-cluster.yml
* remove `selinux` field to cluster configuration. because Docker will resolve it well.
* add `selinux_label` field to `Mount`. it apply to Docker volume option.
* remove `z` option from system directories. system directories should not be relabeled.
=> fix: SELinux support

commands.go, container.go, etcd.go, etcd_strategy.go, etcd_strategy_test.go, images.go, kubeconfig.go, kubernetes.go, kubernetes_strategy.go, kubernetes_strategy_test.go, mtest/suite_test.go, pki.go, status.go
To achieve better performance, the strategy how CKE modifies nodes need to be redesigned.
=> Re-design strategies

cli/etcd.go, cli/kubernetes.go, cli/vault.go, cluster.go, cmd/ckecli/main.go, docs/ckecli.md, etcd.go, etcd_strategy.go, infrastructure.go, kubeconfig.go, mtest/ckecli_test.go, mtest/run_test.go, pki.go, status.go, storage.go
- `ckecli etcd issue`
- `ckecli etcd user-add`
- `ckecli etcd root-issue`
- `ckecli kubernetes issue`
=> Subcommands to issue client certificate

commands.go, kubernetes.go, kubernetes_strategy.go, pki.go
* add kubernetes service names to alt_names
* add MASTER_CLUSTER_IP to ip_sans
refs: https://kubernetes.io/docs/concepts/cluster-administration/certificates/
=> fix kube-apiserver's certificate

op/etcd_add.go
When adding a new server to etcd cluster, the server checks
that the status of the cluster continues healthy at least for the
last 5 seconds.
https://github.com/etcd-io/etcd/blob/fb674833c21e729fe87fff4addcf93b2aa4df9df/etcdserver/server.go#L1562
To satisfy this requirement, addEtcdMemberCommand should
sleep several seconds.
=> Wait several seconds before adding a server to etcd.

images.go, mtest/kubernetes_test.go, op/constants.go, op/kube_clusterdns.go, op/kube_nodedns.go, op/status.go, server/strategy.go, server/strategy_test.go, status.go
* remove unnecessary labels
* fix label key to use `cke.cybozu.com/` as prefix
* remove `loop` plugin on CoreDNS
* update CoreDNS deployment
=> Refactor CoreDNS Strategy

op/kube_nodedns.go
Added options:
* do-daemonize: no
* rrset-roundrobin: yes
* control-interface: 127.0.0.1
=> [node] improve unbound configurations

mtest/operators_test.go, server/node_filter.go
make writing hostnames in cke-cluster.yml possible
=> Fix node resources are removed if hostname is specified

cluster.go, cluster_test.go, docs/cluster.md, docs/logging.md, mtest/kubernetes_test.go, mtest/run_test.go, op/k8s/apiserver_boot.go, op/k8s/apiserver_restart.go, server/node_filter.go, server/strategy_test.go
This pull request allows cke to use audit log
=> Add audit log for kube-apiserver

op/k8s/kubelet_boot.go, op/k8s/kubelet_restart.go
If containerd runtime is specified, pause container image will not exist in docker graph(/var/lib/docker).
=> stop to pull pause container image.

op/k8s/apiserver_boot.go
=> Revert "[op] Add NodeRestriction plugin"

docker-compose/docker-compose.yml, pkg/apply_gen/main.go, resource.go, resource_apply.go
Service resource of the kubernetes can not update because ClsuterIP is already defined.
=> Fix user-defined resources operation

server/strategy.go
Deployments need to be created only after enough nodes become ready.
=> To avoid thundering herd problem.

Makefile, docker/Dockerfile
This pull request made the following changes.
1. fix docker file for handling podman v1.3.2
2. add `GOFLAGS = -mod=vendor` in Makefile
=> Fix dockerfile

docs/ckecli.md, docs/schema.md, mtest/Makefile, mtest/ckecli.go, pkg/ckecli/cmd/sabakan_enable.go, sabakan/integrate.go, storage.go, storage_test.go
"ckecli sabakan disable" no longer removes sabakan URL.
=> [ckecli] add sabakan enable subcommand

cluster.go, cluster_test.go, docs/sabakan-integration.md, mtest/operators.go, mtest/run.go, pkg/ckecli/cmd/cluster_set.go, pkg/ckecli/cmd/sabakan_set_template.go, sabakan/constants.go, sabakan/generator.go, sabakan/generator_test.go, sabakan/template.go, server/control.go
https://github.com/cybozu-go/neco/issues/377
=> sabakan: weighted selection of node roles

sabakan/generator.go, sabakan/generator_test.go, sabakan/op.go, sabakan/op_test.go
https://github.com/cybozu-go/neco/issues/473
=> [cke] Multiple control planes can be selected from the same rack

op/kube_node_remove.go
Node resource is not deleted immediately if it has some finalizers.
To prevent new pods are scheduled on deleting nodes, CKE make
such nodes unschedulable.
=> make deleting node unschedulable like kubectl cordon

.circleci/config.yml, docs/user-resources.md, pkg/apply_gen/main.go, resource.go, resource_apply.go
This pull request is the complement for #214 and made the following changes.
- add `PodDisruptionBudget` for the code generator code
- regenerate codes
=> Generate codes

README.md
Feedback links are required to submit CII best practices badge.
https://bestpractices.coreinfrastructure.org/
=> [ci skip] update README.md

Makefile, docs/ckecli.md, docs/schema.md, mtest/kubernetes.go, mtest/nginx.yml, mtest/operators.go, mtest/run.go, mtest/upgrade.go, phase.go, pkg/ckecli/cmd/status.go, server/control.go, server/strategy.go, server/strategy_test.go, storage.go, storage_test.go
https://github.com/cybozu-go/neco/issues/705
=> Add "ckecli status" and refactor mtest using it.

op/nodedns/nodedns.go
Signed-off-by: dulltz <isrgnoe@gmail.com>
=> node-dns: use TCP to connect upstream

sabakan/generator.go, sabakan/generator_test.go
Signed-off-by: Yuji Ito <llamerada.jp@gmail.com>
=> add label for each role

Makefile, go.mod, images.go, mtest/Makefile, vendor/github.com/coreos/etcd/clientv3/client.go, vendor/github.com/coreos/etcd/clientv3/ctx.go, vendor/github.com/coreos/etcd/clientv3/retry_interceptor.go, vendor/github.com/coreos/etcd/version/version.go, vendor/github.com/coreos/go-semver/LICENSE, vendor/github.com/coreos/go-semver/NOTICE, vendor/github.com/coreos/go-semver/semver/semver.go, vendor/github.com/coreos/go-semver/semver/sort.go, vendor/modules.txt
Signed-off-by: dulltz <isrgnoe@gmail.com>
=> etcd: v3.3.19.1

DEVELOP.md
Signed-off-by: Yuji Ito <llamerada.jp@gmail.com>
=> added about branch policy

mtest/cke-cluster.yml, mtest/node-ign.yml
Signed-off-by: Yuji Ito <llamerada.jp@gmail.com>
=> Remove sudo from node-ign.yml and test

sonobuoy/Makefile, sonobuoy/README.md, sonobuoy/Vagrantfile, sonobuoy/cke-cluster.yml
https://github.com/cybozu-go/neco/issues/833
=> Revert the Makefile target to run sonobuoy with Vagrant

bin/env, bin/env-sonobuoy, docs/cluster.md, docs/sabakan-integration.md, server/node_filter.go, server/strategy_test.go
=> treat node-role labels as internal

bin/env-sonobuoy
=> ci: revert GCP zone for sonobuoy

README.md
=> Replace a container status badge to a text link

mtest/operators.go, mtest/run.go, phase.go, server/strategy.go, server/strategy_test.go
Fix this issue: https://github.com/cybozu-go/neco/issues/951
Skip operations for unreachable nodes to prevent nil pointer exception.
=> Do not attempt to ssh to unreachable nodes.

Makefile, images.go, mtest/Makefile
This PR updates etcd from 3.3.20 to 3.3.22
=> Update etcd to 3.3.22

mtest/operators.go
Signed-off-by: Kazuhito MATSUDA <kazuhito.matuda@gmail.com>
=> mtest: Stop CKE before node shutdown

cluster_test.go
Signed-off-by: Yuji Ito <llamerada.jp@gmail.com>
=> fix degrades introduced by #329

example/flannel-toleration.yaml, example/kustomization.yaml, sonobuoy/Makefile
Since sonobuoy add taints during tests, flannel pods
need to tolerate them.
=> sonobuoy: make flannel pods tolerate any taints

infrastructure.go, sabakan/integrate.go, server/control.go, server/get_status.go
=> Update annotations to calm the latest nilerr.

bin/env, bin/run-mtest.sh, mtest/Makefile, mtest/host.ign, mtest/node-ign.yml
and use C2 instance with NVMe local SSD
=> mtest: return to GCP's asia-northeast1-c

pkg/ckecli/cmd/vault_init.go
by adding logs for what it has done.
=> ckecli: make "vault init" subcommand nice

README.md, docs/ckecli.md, docs/cluster.md, docs/constraints.md, docs/design.md, docs/reboot.md, docs/schema.md
=> Node maintenance: reboot nodes gracefully

docs/reboot.md, reboot.go, storage.go, storage_test.go
This pull request implements the data struct and the storage API for node reboot functionality.
=> Implement Node Reboot Storage API

cluster.go, constraints.go, docs/ckecli.md, docs/cluster.md, docs/constraints.md, docs/reboot.md, go.mod, op/reboot.go, op/reboot_dequeue.go, operation.go, phase.go, pkg/ckecli/cmd/reboot_queue_cancel.go, reboot.go, record.go, server/control.go, server/strategy.go, server/strategy_test.go
This PR implements reboot feature and strategy test.
=> Reboot nodes

cluster_test.go, cluster_test.yaml, mtest/Makefile, mtest/cke-cluster.yml, mtest/env_test.go, mtest/operators_test.go, mtest/reboot-deployment.yaml, op/reboot.go
This PR fixes reboot implementation and adds necessary tests.
=> reboot: implement mtest

docs/cluster.md
=> Fix LabelSelector link in cluster.md

cluster_test.go, cluster_test.yaml
Test for https://github.com/cybozu-go/neco/issues/988.
=> Add kube-scheduler profile test

docs/ckecli.md, pkg/ckecli/cmd/reboot_queue_is_enabled.go, pkg/ckecli/cmd/sabakan_is_enabled.go
=> Add ckecli commands to show sabakan and reboot-queue status

server/strategy.go, server/strategy_test.go
=> Skip reboot if etcd cluster is not responding and in-sync.

tools/rivers/README.md, tools/rivers/health.go, tools/rivers/main.go, tools/rivers/server.go
=> Add upstream health checking to rivers

mtest/Makefile, mtest/cluster.yml, mtest/host.ign, mtest/node-ign.yml
=> Apply Placemat v2

.github/workflows/release-images.yaml
Signed-off-by: binoue <banji-inoue@cybozu.co.jp>
=> fix image name

.github/workflows/release-images.yaml
Signed-off-by: binoue <banji-inoue@cybozu.co.jp>
=> Add checkout step

.github/workflows/release-images.yaml
Signed-off-by: binoue <banji-inoue@cybozu.co.jp>
=> add missing v prefix to release

server/control.go
https://github.com/cybozu-go/cke/issues/432
=> Exit CKE when vault returns 403

tools/Makefile, tools/rivers/di_test.go, tools/rivers/health.go, tools/rivers/health_test.go, tools/rivers/server.go, tools/rivers/server_test.go, tools/rivers/upstream_test.go
=> add unit tests for rivers

tools/CHANGELOG.md, tools/Makefile
=> Update CNI plugin to 0.9.1

.github/workflows/release-tools.yaml
=> Fix release tools workflow

.github/workflows/release-tools.yaml
=> Fix release cke-tools workflow

server/strategy_test.go, static/cluster-dns.yml, static/resources.go
=> Update revision cke.cybozu.com/revision

mtest/README.md
Update mtest README because its content looked outdated.
=> Update mtest README

LICENSE, README.md
- Change LICENSE file
- Edit README.md for license
=> Change LICENSE from MIT to Apache2.0

docs/reboot.md, mtest/assets_test.go, mtest/operators_test.go, mtest/reboot-deployment.yaml, mtest/reboot-job-completed.yaml, mtest/reboot-job-running.yaml, op/reboot.go
https://github.com/cybozu-go/neco/issues/1756
=> Prevent to evict job pods

DEVELOP.md, tools/CHANGELOG.md, tools/Makefile
=> Update cke-tools for CNI Plugins 1.0.1

op/k8s/apiserver_restart.go
=> Enable "DenyServiceExternalIPs" admission plugin

example/docker-compose.yml
=> Update image tag for docker-compose

go.mod, go.sum, pkg/ckecli/cmd/vault_init.go
part of https://github.com/cybozu-go/cke/issues/484
=> use term package instead of gopass

tools/CHANGELOG.md
Usually, we use the latest CNI plugin in this PR. But it is not updated (still same version).
=> update CHANGELOG for cke-tools

CHANGELOG.md, version.go
=> Bump version to 1.22.0

op/constants.go, op/k8s/controller_manager_boot.go, op/k8s/scheduler_boot.go
=> add authn/authz kubeconfig options to controller-manager/scheduler

CHANGELOG.md, version.go
=> Bump version to 1.22.1

docker/.gitignore
=> gitignore some new artifacts

tools/CHANGELOG.md, tools/Makefile
https://github.com/cybozu-go/cke/blob/main/DEVELOP.md#update-cke-tools
https://github.com/cybozu-go/cke/blob/main/tools/RELEASE.md
=> cke-tools: Update CNI plugins to v1.1.1

CHANGELOG.md, version.go
part of https://github.com/cybozu-go/cke/issues/545
=> Bump version to 1.23.0-rc.1

example/docker-compose.yml
=> Update CKE image for example

sonobuoy/PRODUCT.yaml
The product_logo_url must be a direct link to an image file.
ref: https://github.com/cncf/k8s-conformance/pull/2097#issuecomment-1212913744
=> Update product logo URL

CHANGELOG.md, cluster.go, cluster_test.go, docs/cluster.md, docs/sabakan-integration.md, localproxy/infrastructure.go, mtest/cke-cluster.yml, sabakan/generator.go, sabakan/generator_test.go, sabakan/integrate.go, sabakan/score.go, server/control.go, server/integrator.go, testdata/cluster.yaml
=> Don't use tainted node as control plane node

CHANGELOG.md, images.go
Forgot in https://github.com/cybozu-go/cke/pull/591/files
Signed-off-by: kouki <kouworld0123@gmail.com>
=> Use Kubernetes 1.24.9

CHANGELOG.md, images.go
This fixes git vulnerabilities
- USN-5810-1: Git vulnerabilities
- USN-5810-2: Git regression
Signed-off-by: kouki <kouworld0123@gmail.com>
=> Update kubernetes image version to 1.24.9.3

CHANGELOG.md, version.go
zeroalphat <taichi-takemura@cybozu.co.jp>
=> Bump version to 1.25.0-rc.1

CHANGELOG.md, version.go
Signed-off-by: zeroalphat <taichi-takemura@cybozu.co.jp>
=> Bump version to 1.25.0

CHANGELOG.md, container.go, docs/cluster.md, go.mod, go.sum
Signed-off-by: zeroalphat <taichi-takemura@cybozu.co.jp>
=> Change behavior to not do SELinux labeling unless SELinux enforcing mode 

cluster.go, cluster_test.go, docs/cluster.md, op/reboot.go, testdata/cluster.yaml
=> Retry reboot command if failed in processing reboot queue

CHANGELOG.md
=> Update CHANGELOG for retry-reboot

mtest/kubernetes_test.go, resource.go, server/strategy.go, server/strategy_test.go
I fixed the resource applying logic.
If resources have the same rank, cke applies these resources simultaneously. 
Signed-off-by: terasihma <tomoya-terashima@cybozu.co.jp>
=> fix to apply resources that has same rank at the same time

server/control.go
Signed-off-by: terasihma <tomoya-terashima@cybozu.co.jp>
=> Fix to call addon on k8sMaintain phase

server/control.go
Signed-off-by: terasihma <tomoya-terashima@cybozu.co.jp>
=> Add a comment for the added condition whether calling the addon

op/reboot.go
=> Fix retry of reboot to set timeout in each retry

CHANGELOG.md, cluster.go, cluster_test.go, docs/cluster.md, op/reboot.go, testdata/cluster.yaml
=> Add setting of reboot retry interval

mtest/assets_test.go, mtest/httpd.yml, mtest/kubernetes_test.go, mtest/reboot-deployment.yaml
This PR renames pod and containers for mtest.
=> Rename test pod and containers

CHANGELOG.md, cluster.go, cluster_test.go, docs/cluster.md, op/reboot.go, testdata/cluster.yaml
This PR backports #645 to 1.25 branch.
=> Backport #645 to add setting of reboot retry interval

CHANGELOG.md, version.go
=> Bump version to 1.25.9

CHANGELOG.md, server/watch.go
=> Fix to check error of etcd watch response

CHANGELOG.md, version.go
=> Bump version to 1.26.4

docs/ckecli.md, mtest/kubernetes_test.go, pkg/ckecli/cmd/resource_get.go
=> Implement ckecli resource get

tools/rivers/main.go, vault.go
=> Remove deprecated DualStack flag

mtest/cke-cluster.yml, mtest/repair_test.go
=> Add test for too long repair execution

CHANGELOG.md, constraints.go, docs/ckecli.md, docs/constraints.md, docs/sabakan-integration.md, docs/sabakan-triggered-repair.md, mtest/ckecli_test.go, pkg/ckecli/cmd/auto_repair.go, pkg/ckecli/cmd/auto_repair_disable.go, pkg/ckecli/cmd/auto_repair_enable.go, pkg/ckecli/cmd/auto_repair_get_variables.go, pkg/ckecli/cmd/auto_repair_is_enabled.go, pkg/ckecli/cmd/auto_repair_set_variables.go, pkg/ckecli/cmd/constraints_set.go, pkg/ckecli/cmd/sabakan_get_variables.go, sabakan/integrate.go, sabakan/mock/resolver.go, sabakan/query.go, sabakan/query_test.go, sabakan/repairer.go, sabakan/repairer_test.go, storage.go, storage_test.go
=> Add sabakan-triggered automatic repair functionality

mtest/reboot_test.go
=> mtest: refactor reboot test code

tools/Makefile
=> update CNI plugin to 1.5.1

CHANGELOG.md, version.go
- **update kubernetes to 1.28.12 (#756)**
- **Bump version to 1.28.7**
=> bump 1.28.7

CHANGELOG.md, version.go
=> Bump version to 1.29.0-rc.2

bin/env
in order to follow changes in the PR below.
- https://github.com/cybozu-go/neco/pull/2688
=> increase BOOT_DISK_SIZE to 30GB

op/k8s/kubelet_boot.go
=> Set /sys mount of kubelet as read-write(backport of #773)

CHANGELOG.md, docs/sabakan-integration.md, sabakan/generator.go, sabakan/generator_test.go
backport of https://github.com/cybozu-go/cke/pull/780
=> Revive unreachable taint (backport of #780)

version.go
sonobuoy https://github.com/cybozu-go/cke/actions/runs/13851122661
=> Bump version to 1.31.0-rc.1

cluster.go, cluster_test.go, docs/cluster.md, server/strategy.go, server/strategy_test.go
sobobuoy
- https://github.com/cybozu-go/cke/actions/runs/15182083525
=> add option to skip kubelet update

tools/CHANGELOG.md
part of https://github.com/cybozu-go/cke/issues/799
=> Bump cke-tools version to 1.32.0

.github/workflows/main.yaml, Makefile, example/docker-compose.yml, images.go, mtest/Makefile, op/etcd/common.go, sonobuoy/docker-compose.yml
This PR updates etcd to v3.6.5.
=> Udpate etcd to v3.6.5
